# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  kdtree-regional-benchmarks:
    dependencies:
    - base
    - kdtree-regional
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: kdtree-regional is a new Haskeleton package.
executables:
  kdtree-regional:
    dependencies:
    - base
    - kdtree-regional
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: mlitchard/kdtree-regional
library:
  dependencies:
  - base
  source-dirs: library
license: MIT
maintainer: Michael Litchard
name: kdtree-regional
synopsis: A new Haskeleton package.
tests:
  kdtree-regional-test-suite:
    dependencies:
    - base
    - kdtree-regional
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
